name: SunLight
main: su.nightexpress.sunlight.SunLight
version: '${project.version}'
description: Advanced, Light & Modern all-in-one server management plugin.
author: NightExpress
depend: [ NexEngine ]
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - Essentials
api-version: 1.17