name: SunLight
main: su.nightexpress.sunlight.SunLightPlugin
version: '${project.version}'
description: Advanced, light & modern all-in-one server management plugin.
author: NightExpress
depend: [ nightcore ]
softdepend:
  - PlaceholderAPI
  - ProtocolLib
api-version: 1.18